const translations = {
    en: {
        // Home
        heroTitle: "Capture the Flow of Reading",
        heroSub: "<span class='hero-highlight'>Build your private knowledge system.</span> OmniFlows transforms fragmented reading sessions into structured assets.",
        ctaLearnMore: "Try Now",
        demoCapture: "One-click Capture: Semantic context preserved.",
        demoReview: "Knowledge Review: Daily insights generated by AI.",
        demoInsight: "Daily Digest: AI-driven themes and takeaways.",
        demoSync: "Seamless Sync: Obsidian, Notion & Google Drive.",
        whyOmniFlows: "Why OmniFlows?",
        case1Title: "Reading Depth Model",
        case1Text: "We don't just track time. We measure dwell time and scroll depth to distinguish curiosity from deep study.",
        case2Title: "Semantic Block Capture",
        case2Text: "Capture complete logical units, not just sentences. Every highlight retains its original context automatically.",
        case3Title: "Cross-Platform Sync",
        case3Text: "Your knowledge assets exported directly to Obsidian, Notion, or your private cloud.",
        case4Title: "Custom Tagging",
        case4Text: "Organize your highlights with multi-select tags. Perfect for building a thematic knowledge system.",
        integHeader: "Knowledge Export. Seamless Persistence.",
        integSub: "OmniFlows ensures your data never becomes an island. Build your lifelong knowledge base through deep cross-platform integration.",
        integ1Title: "Obsidian Sync",
        integ1Text: "Real-time synchronization of browsing trajectories and knowledge items to your Obsidian vault.",
        integ2Title: "Google Drive Backup",
        integ2Text: "Securely back up all captured data and configuration to your personal cloud.",
        integ3Title: "Local LLM Support",
        integ3Text: "Run categorization and summarization locally for maximum privacy and performance.",
        integ4Title: "Notion Integration",
        integ4Text: "Directly store and organize your highlights in Notion databases with automated properties.",
        footerTagline: "Building the future of digital memory.",
        footerResources: "Integration Guide",
        footerSupport: "Support",
        footerLegal: "Legal",
        footerPrivacy: "Privacy Policy",
        footerObsidianGuide: "Obsidian",
        footerNotionGuide: "Notion",

        // Obsidian Setup
        obsidianTitle: "Obsidian Integration Guide",
        obsidianSubtitle: "Setup the Local REST API to connect OmniFlows to your vault.",
        obsidianStep1: "Install Local REST API",
        obsidianStep1Text: "OmniFlows communicates with Obsidian using the Local REST API community plugin.",
        obsidianStep1Item1: "Open Obsidian Settings and go to Community plugins.",
        obsidianStep1Item2: "Click Browse and search for Local REST API.",
        obsidianStep1Item3: "Click Install and then Enable.",
        obsidianStep2: "Get Your API Key",
        obsidianStep2Text: "Once enabled, you need to copy the authorization token.",
        obsidianStep2Item1: "Go to the Local REST API settings within Obsidian.",
        obsidianStep2Item2: "Find the API Key section.",
        obsidianStep2Item3: "Click the Copy button or manually copy the long string of characters.",
        obsidianStep3: "Configure OmniFlows",
        obsidianStep3Text: "Open OmniFlows Extension Options page and fill in the details:",
        obsidianStep3Protocol: "Protocol: Choose http.",
        obsidianStep3Port: "Port: Usually 27123. Check your plugin settings if unsure.",
        obsidianStep3Key: "API Key: Paste the key you copied in Step 2.",
        obsidianTrouble1Title: "Connection Failed?",
        obsidianTrouble1Text1: "Protocol Mismatch: Ensure you selected http in OmniFlows. HTTPS is currently not supported due to browser security restrictions.",
        obsidianTrouble1Text2: "Plugin Status: Ensure the plugin status in Obsidian is 'Active' (Green indicator).",
        obsidianTrouble1Text3: "Port Conflict: Check if another application is using the same port.",

        // Notion Setup
        notionTitle: "Notion Integration Guide",
        notionSubtitle: "Connect OmniFlows to your Notion workspace to sync knowledge seamlessly.",
        notionStep1: "Create an Integration",
        notionStep1Text: "You need an 'Internal Integration' to allow the extension to access your Notion pages.",
        notionStep1Item1: "Go to notion.so/my-integrations.",
        notionStep1Item2: "Click + New integration.",
        notionStep1Item3: "Give it a name like OmniFlows and click Submit.",
        notionStep1Item4: "Copy the Internal Integration Secret. This is your API Token.",
        notionStep2: "Prepare the Page & Connection",
        notionStep2Text: "Notion requires you to explicitly grant an integration access to a page.",
        notionStep2Item1: "Create a new Page in Notion (e.g., 'My Research').",
        notionStep2Item2: "Click the ... (three dots) in the top right corner of the page.",
        notionStep2Item3: "Select Add connections and search for the OmniFlows integration you just created.",
        notionStep2Item4: "Confirm the connection.",
        notionStep3: "Get the Page ID",
        notionStep3Text: "OmniFlows needs to know where to create your research database.",
        notionStep3Item1: "Copy the URL of the page you just created.",
        notionStep3Item2: "The Page ID is the 32-character string at the end of the URL.",
        notionExampleUrl: "Example URL:",
        notionExampleId: "The ID is 347eb299574480fe9d9bdcaf8cf9be41.",
        notionStep4: "Finalize in OmniFlows",
        notionStep4Text: "In OmniFlows Options, paste your Integration Secret and Page ID.",
        notionAutoSetupTitle: "Automatic Setup",
        notionAutoSetupText: "OmniFlows will automatically create a structured database when you save your first capture.",
        notionTrouble1Title: "Object not found",
        notionTrouble1Text1: "Ensure you have completed Step 2. You must manually 'Add Connection' to the page in Notion.",
        notionTrouble2Title: "Database ID vs Page ID:",
        notionTrouble2Text1: "If you are connecting to an existing database, use its ID. Otherwise, use the Page ID.",

        // Common
        troubleshootingTitle: "Troubleshooting",
        backToHome: "← Back to Home"
    },
    "zh-CN": {
        // Home
        heroTitle: "捕获阅读之流",
        heroSub: "<span class='hero-highlight'>以此构建您的私域知识体系。</span>OmniFlows 捕捉阅读轨迹，将碎片化浏览转化为结构化知识资产。",
        ctaLearnMore: "立即体验",
        demoCapture: "一键捕捉：自动保留语义块完整上下文。",
        demoReview: "知识回顾：AI 生成的每日洞察与总结。",
        demoInsight: "每日摘要：AI 驱动的主题与要点抽取。",
        demoSync: "无缝同步：已支持 Obsidian, Notion 与 Google Drive。",
        whyOmniFlows: "为何选择 OmniFlows?",
        case1Title: "阅读深度模型",
        case1Text: "不只是计时。我们通过停顿和滚动深度识别真正的深读行为。",
        case2Title: "语义块捕捉",
        case2Text: "捕捉完整的逻辑单元。每一个高亮都自动保留其原始语义背景。",
        case3Title: "跨平台同步",
        case3Text: "将你的知识资产直接导出到 Obsidian、Notion 或私有云。",
        case4Title: "自定义标签",
        case4Text: "通过多选标签组织你的高亮，助你构建主题化的知识体系。",
        integHeader: "知识导出，无缝持久",
        integSub: "OmniFlows 确保你的数据不再是孤岛。通过深度的跨平台集成，构建你的终身知识库。",
        integ1Title: "Obsidian 同步",
        integ1Text: "实时将浏览轨迹和知识项同步到你的 Obsidian 库。",
        integ2Title: "Google Drive 备份",
        integ2Text: "安全地将所有捕获的数据和配置备份到你的个人云端。",
        integ3Title: "本地大模型支持",
        integ3Text: "在本地运行分类和摘要，实现最高的隐私和性能。",
        integ4Title: "Notion 集成",
        integ4Text: "将高亮直接存储到 Notion 数据库，并自动填充结构化属性。",
        footerTagline: "构建数字记忆的未来。",
        footerResources: "集成指南",
        footerSupport: "技术支持",
        footerLegal: "法律条款",
        footerPrivacy: "隐私政策",
        footerObsidianGuide: "Obsidian",
        footerNotionGuide: "Notion",

        // Obsidian Setup
        obsidianTitle: "Obsidian 集成指南",
        obsidianSubtitle: "配置 Local REST API 插件，将 OmniFlows 连接至您的笔记库。",
        obsidianStep1: "安装插件",
        obsidianStep1Text: "OmniFlows 通过 Local REST API 插件与 Obsidian 通信。",
        obsidianStep1Item1: "打开 Obsidian 设置，进入“第三方插件 (Community plugins)”。",
        obsidianStep1Item2: "点击“浏览 (Browse)”并搜索 Local REST API。",
        obsidianStep1Item3: "点击安装并启用插件。",
        obsidianStep2: "获取 API Key",
        obsidianStep2Text: "启用后，您需要复制授权令牌。",
        obsidianStep2Item1: "进入 Local REST API 插件的设置页面。",
        obsidianStep2Item2: "找到 API Key 部分。",
        obsidianStep2Item3: "点击复制按钮，或手动获取那段长字符串令牌。",
        obsidianStep3: "配置插件能力",
        obsidianStep3Text: "打开 OmniFlows 插件的“选项”页面并填写：",
        obsidianStep3Protocol: "Protocol: 请选择 http。",
        obsidianStep3Port: "Port: 通常为 27123。",
        obsidianStep3Key: "API Key: 粘贴你在上一步复制的密钥。",
        obsidianTrouble1Title: "连接失败？",
        obsidianTrouble1Text1: "协议不匹配：确保在 OmniFlows 中选择了 http。目前不支持 HTTPS。",
        obsidianTrouble1Text2: "插件状态：确保 Obsidian 中的插件状态显示为绿色“Active”。",
        obsidianTrouble1Text3: "端口冲突：检查是否有其他程序占用了相同的端口。",

        // Notion Setup
        notionTitle: "Notion 集成指南",
        notionSubtitle: "将 OmniFlows 连接至 Notion 工作区，实现知识无缝同步。",
        notionStep1: "创建分身 (Integration)",
        notionStep1Text: "您需要创建一个“内部分身”来允许插件访问您的 Notion 页面。",
        notionStep1Item1: "访问 notion.so/my-integrations。",
        notionStep1Item2: "点击 “+ New integration”。",
        notionStep1Item3: "命名为 OmniFlows 并提交。",
        notionStep1Item4: "复制 “Internal Integration Secret”，这就是你的 API 令牌。",
        notionStep2: "准备页面并进行关联",
        notionStep2Text: "Notion 要求您显式授予分身对页面的访问权限。",
        notionStep2Item1: "在 Notion 中创建一个新页面（例如“我的研究”）。",
        notionStep2Item2: "点击页面右上角的 “...” 按钮。",
        notionStep2Item3: "选择 “Add connections” (添加连接) 并搜索你刚才创建的 OmniFlows。",
        notionStep2Item4: "确认关联。",
        notionStep3: "获取 Page ID",
        notionStep3Text: "OmniFlows 需要知道在何处创建您的研究数据库。",
        notionStep3Item1: "复制该页面的链接。",
        notionStep3Item2: "链接末尾那串 32 位的字符即为 Page ID。",
        notionExampleUrl: "示例链接：",
        notionExampleId: "ID 是 347eb299574480fe9d9bdcaf8cf9be41。",
        notionStep4: "在插件中完成设置",
        notionStep4Text: "在 OmniFlows 选项中，粘贴您的集成密钥和页面 ID。",
        notionAutoSetupTitle: "自动化设置",
        notionAutoSetupText: "当你保存第一次捕获时，OmniFlows 会在该页面下自动创建一个数据库。",
        notionTrouble1Title: "找不到对象？",
        notionTrouble1Text1: "请确认已完成第 2 步。你必须手动在该页面上“添加连接”到 OmniFlows。",
        notionTrouble2Title: "数据库 ID vs 页面 ID：",
        notionTrouble2Text1: "如果你连接的是现有数据库，请使用其 ID。否则请使用页面 ID。",

        // Common
        troubleshootingTitle: "故障排查",
        backToHome: "← 返回首页"
    },
    de: {
        // Home
        heroTitle: "Den Lesefluss erfassen",
        heroSub: "<span class='hero-highlight'>Bauen Sie Ihr privates Wissenssystem auf.</span> OmniFlows verwandelt fragmentiertes Lesen in strukturierte Wissenswerte.",
        ctaLearnMore: "Jetzt ausprobieren",
        demoCapture: "Ein-Klick-Erfassung: Semantischer Kontext bleibt erhalten.",
        demoReview: "Wissensrueckblick: Taegliche KI-Einblicke.",
        demoInsight: "Daily Digest: KI-gesteuerte Themen.",
        demoSync: "Nahtlose Synchronisation: Obsidian, Notion & Google Drive.",
        whyOmniFlows: "Warum OmniFlows?",
        case1Title: "Lesetiefen-Modell",
        case1Text: "Wir messen nicht nur die Zeit. Wir analysieren die Verweildauer und Scrolltiefe.",
        case2Title: "Semantische Block-Erfassung",
        case2Text: "Erfassen Sie logische Einheiten, nicht nur Saetze.",
        case3Title: "Plattformuebergreifender Sync",
        case3Text: "Exportieren Sie direkt in Obsidian, Notion oder Ihre private Cloud.",
        case4Title: "Benutzerdefiniertes Tagging",
        case4Text: "Organisieren Sie Ihre Highlights mit Multi-Select-Tags.",
        integHeader: "Wissensexport. Nahtlose Beständigkeit.",
        integSub: "OmniFlows stellt sicher, dass Ihre Daten nie zu einer Insel werden.",
        integ1Title: "Obsidian Sync",
        integ1Text: "Echtzeit-Synchronisation von Browsing-Trajektorien in Ihren Obsidian-Tresor.",
        footerTagline: "Die Zukunft des digitalen Gedaechtnisses bauen.",
        footerResources: "Integrationshilfe",
        footerSupport: "Support",
        footerLegal: "Rechtliches",
        footerPrivacy: "Datenschutz",
        footerObsidianGuide: "Obsidian",
        footerNotionGuide: "Notion",

        // Obsidian Setup
        obsidianTitle: "Obsidian Integrationsanleitung",
        obsidianSubtitle: "Richten Sie die Local REST API ein, um OmniFlows mit Ihrem Tresor zu verbinden.",
        obsidianStep1: "Installieren Sie die Local REST API",
        obsidianStep1Text: "OmniFlows kommuniziert mit Obsidian über das Community-Plugin Local REST API.",
        obsidianStep1Item1: "Öffnen Sie die Obsidian-Einstellungen und gehen Sie zu Community-Plugins.",
        obsidianStep1Item2: "Klicken Sie auf Durchsuchen und suchen Sie nach Local REST API.",
        obsidianStep1Item3: "Klicken Sie auf Installieren und dann auf Aktivieren.",
        obsidianStep2: "Holen Sie sich Ihren API-Schlüssel",
        obsidianStep2Text: "Nach der Aktivierung müssen Sie den Autorisierungstoken kopieren.",
        obsidianStep2Item1: "Gehen Sie zu den Einstellungen der Local REST API in Obsidian.",
        obsidianStep2Item2: "Suchen Sie den Abschnitt API-Schlüssel.",
        obsidianStep2Item3: "Klicken Sie auf Kopieren.",
        obsidianStep3: "OmniFlows konfigurieren",
        obsidianStep3Text: "Öffnen Sie die OmniFlows-Optionen und füllen Sie die Details aus:",
        obsidianStep3Protocol: "Protokoll: Wählen Sie http.",
        obsidianStep3Port: "Port: Normalerweise 27123.",
        obsidianStep3Key: "API-Schlüssel: Fügen Sie den Schlüssel ein.",
        obsidianTrouble1Title: "Verbindung fehlgeschlagen?",
        obsidianTrouble1Text1: "Protokoll-Fehler: Stellen Sie sicher, dass http ausgewählt ist.",
        obsidianTrouble1Text2: "Plugin-Status: Stellen Sie sicher, dass es 'Aktiv' ist.",
        obsidianTrouble1Text3: "Port-Konflikt: Prüfen Sie auf andere Anwendungen.",

        // Notion Setup
        notionTitle: "Notion Integrationsanleitung",
        notionSubtitle: "Verbinden Sie OmniFlows mit Ihrem Notion-Workspace.",
        notionStep1: "Integration erstellen",
        notionStep1Text: "Sie benötigen eine 'Interne Integration'.",
        notionStep1Item1: "Gehen Sie zu notion.so/my-integrations.",
        notionStep1Item2: "Klicken Sie auf + New integration.",
        notionStep1Item3: "Name angeben und speichern.",
        notionStep1Item4: "Kopieren Sie das Secret.",
        notionStep2: "Verbindung herstellen",
        notionStep2Text: "Geben Sie die Integration auf einer Seite frei.",
        notionStep2Item1: "Neue Seite in Notion erstellen.",
        notionStep2Item2: "Klicken Sie auf '...'.",
        notionStep2Item3: "Verbindung hinzufügen und OmniFlows suchen.",
        notionStep2Item4: "Bestätigen.",
        notionStep3: "Seiten-ID holen",
        notionStep3Text: "Holen Sie die ID aus der URL.",
        notionStep3Item1: "URL der Seite kopieren.",
        notionStep3Item2: "Die ID ist die 32-stellige Zeichenfolge am Ende.",
        notionExampleUrl: "Beispiel-URL:",
        notionExampleId: "Die ID ist ...",
        notionStep4: "In OmniFlows abschließen",
        notionStep4Text: "Fügen Sie Secret und ID in die Optionen ein.",
        notionAutoSetupTitle: "Automatisches Setup",
        notionAutoSetupText: "OmniFlows erstellt die Datenbank automatisch.",
        notionTrouble1Title: "Objekt nicht gefunden",
        notionTrouble1Text1: "Prüfen Sie Schritt 2 (Verbindung hinzufügen).",
        notionTrouble2Title: "Datenbank-ID vs. Seiten-ID:",
        notionTrouble2Text1: "Normalerweise wird die Seiten-ID verwendet.",

        // Common
        troubleshootingTitle: "Fehlerbehebung",
        backToHome: "← Zurück zur Startseite"
    },
    fr: {
        // Home
        heroTitle: "Capturez le flux de lecture",
        heroSub: "<span class='hero-highlight'>Bâtissez votre système de connaissances privé.</span> OmniFlows transforme vos lectures fragmentées en actifs structurés.",
        ctaLearnMore: "Essayer maintenant",
        demoCapture: "Capture en un clic : le contexte semantique est preserve.",
        demoReview: "Revue de connaissances : apercus quotidiens par l'IA.",
        demoInsight: "Digest quotidien : themes et points cles par l'IA.",
        demoSync: "Synchro transparente : Obsidian, Notion et Google Drive.",
        why开门见山: "Pourquoi OmniFlows ?",
        case1Title: "Modele de profondeur de lecture",
        case1Text: "Nous mesurons le temps de lecture et la profondeur de defilement.",
        case2Title: "Capture de blocs semantiques",
        case2Text: "Capturez des unites logiques completes.",
        case3Title: "Synchro multiplateforme",
        case3Text: "Exportez directement vers Obsidian, Notion ou votre cloud prive.",
        case4Title: "Marquage personnalisé",
        case4Text: "Organisez vos points forts with des balises multi-sélection.",
        integHeader: "Export de connaissances. Persistance sans faille.",
        integSub: "OmniFlows garantit que vos données ne deviennent jamais une île.",
        integ1Title: "Obsidian Sync",
        integ1Text: "Synchronisation en temps réel vers votre coffre Obsidian.",
        footerTagline: "Construire l'avenir de la memoire numerique.",
        footerResources: "Guides d'intégration",
        footerSupport: "Assistance",
        footerLegal: "Mentions légales",
        footerPrivacy: "Confidentialité",
        footerObsidianGuide: "Obsidian",
        footerNotionGuide: "Notion",

        // Obsidian Setup
        obsidianTitle: "Guide d'intégration Obsidian",
        obsidianSubtitle: "Configurez Local REST API pour connecter OmniFlows à votre coffre.",
        obsidianStep1: "Installer Local REST API",
        obsidianStep1Text: "OmniFlows communique avec Obsidian via l'extension communautaire Local REST API.",
        obsidianStep1Item1: "Ouvrez les paramètres d'Obsidian et allez dans Community plugins.",
        obsidianStep1Item2: "Cliquez sur Browse et cherchez Local REST API.",
        obsidianStep1Item3: "Installez et activez l'extension.",
        obsidianStep2: "Obtenir votre clé API",
        obsidianStep2Text: "Une fois activée, copiez le jeton d'autorisation.",
        obsidianStep2Item1: "Allez dans les réglages de Local REST API dans Obsidian.",
        obsidianStep2Item2: "Trouvez la section API Key.",
        obsidianStep2Item3: "Cliquez sur Copier.",
        obsidianStep3: "Configurer OmniFlows",
        obsidianStep3Text: "Ouvrez les options d'OmniFlows et remplissez les détails :",
        obsidianStep3Protocol: "Protocole : Choisissez http.",
        obsidianStep3Port: "Port : Généralement 27123.",
        obsidianStep3Key: "Clé API : Collez la clé.",
        obsidianTrouble1Title: "Échec de la connexion ?",
        obsidianTrouble1Text1: "Erreur de protocole : Vérifiez que http est sélectionné.",
        obsidianTrouble1Text2: "Statut : Vérifiez que l'extension est 'Active'.",
        obsidianTrouble1Text3: "Conflit de port : Vérifiez les autres applications.",

        // Notion Setup
        notionTitle: "Guide d'intégration Notion",
        notionSubtitle: "Connectez OmniFlows à votre espace Notion.",
        notionStep1: "Créer une intégration",
        notionStep1Text: "Vous avez besoin d'une 'Intégration Interne'.",
        notionStep1Item1: "Allez sur notion.so/my-integrations.",
        notionStep1Item2: "Cliquez sur + New integration.",
        notionStep1Item3: "Donnez un nom et enregistrez.",
        notionStep1Item4: "Copiez le Secret.",
        notionStep2: "Préparer la page",
        notionStep2Text: "Autorisez l'accès sur une page Notion.",
        notionStep2Item1: "Créez une nouvelle page.",
        notionStep2Item2: "Cliquez sur '...'.",
        notionStep2Item3: "Ajouter des connexions et cherchez OmniFlows.",
        notionStep2Item4: "Confirmez.",
        notionStep3: "Récupérer l'ID de page",
        notionStep3Text: "L'ID se trouve dans l'URL.",
        notionStep3Item1: "Copiez l'URL de la page.",
        notionStep3Item2: "L'ID est la chaîne de 32 caractères à la fin.",
        notionExampleUrl: "Exemple d'URL :",
        notionExampleId: "L'ID est ...",
        notionStep4: "Terminer dans OmniFlows",
        notionStep4Text: "Collez le Secret et l'ID dans les options.",
        notionAutoSetupTitle: "Configuration automatique",
        notionAutoSetupText: "OmniFlows créera la base de données automatiquement.",
        notionTrouble1Title: "Objet non trouvé",
        notionTrouble1Text1: "Vérifiez l'étape 2 (Ajouter une connexion).",
        notionTrouble2Title: "ID de base vs ID de page :",
        notionTrouble2Text1: "Utilisez l'ID de la page par défaut.",

        // Common
        troubleshootingTitle: "Dépannage",
        backToHome: "← Retour à l'accueil"
    },
    ja: {
        // Home
        heroTitle: "読解の「流」を捉える",
        heroSub: "<span class='hero-highlight'>私域の知識体系を構築する。</span>OmniFlows は読解の軌跡を捉え、断片的な閲覧を知識資産へと変換します。",
        ctaLearnMore: "今すぐ体験",
        demoCapture: "ワンクリック・キャプチャ：セマンティック・コンテキストを自動保存。",
        demoReview: "ナレッジ・レビュー：AI が生成する日々の洞察。",
        demoInsight: "デイリー・ダイジェスト：AIによるテーマ抽出。",
        demoSync: "シームレスな同期：Obsidian, Notion, Google Drive に対応。",
        whyOmniFlows: "なぜ OmniFlows なのか？",
        case1Title: "読解深度モデル",
        case1Text: "単なる時間追跡ではありません。滞留時間とスクロール深度で真の学習を測定します。",
        case2Title: "セマンティック・ブロック・キャプチャ",
        case2Text: "文だけでなく、論理的な単位全体をキャプチャします。",
        case3Title: "クロスプラットフォーム同期",
        case3Text: "Obsidian や Notion、あるいはプライベートクラウドへ直接エクスポート。",
        case4Title: "カスタムタグ",
        case4Text: "マルチセレクトタグでハイライトを整理。",
        integHeader: "知識のエクスポート。シームレスな永続性。",
        integSub: "OmniFlowsはあなたのデータが孤島にならないようにします。",
        integ1Title: "Obsidian同期",
        integ1Text: "閲覧軌跡や知識項目をリアルタイムでObsidianに同期します。",
        footerTagline: "デジタル記憶の未来を築く。",
        footerResources: "統合ガイド",
        footerSupport: "サポート",
        footerLegal: "法的事項",
        footerPrivacy: "プライバシーポリシー",
        footerObsidianGuide: "Obsidian",
        footerNotionGuide: "Notion",

        // Obsidian Setup
        obsidianTitle: "Obsidian 統合ガイド",
        obsidianSubtitle: "Local REST API を設定して、OmniFlows をヴォルトに接続します。",
        obsidianStep1: "Local REST API のインストール",
        obsidianStep1Text: "OmniFlows は Local REST API コミュニティプラグインを使用して Obsidian と通信します。",
        obsidianStep1Item1: "Obsidian の設定を開き、コミュニティプラグインに移動します。",
        obsidianStep1Item2: "「閲覧」をクリックし、Local REST API を検索します。",
        obsidianStep1Item3: "インストールして有効化します。",
        obsidianStep2: "API キーの取得",
        obsidianStep2Text: "有効化後、認証トークンをコピーする必要があります。",
        obsidianStep2Item1: "Obsidian 内の Local REST API 設定に移動します。",
        obsidianStep2Item2: "API キーのセクションを見つけます。",
        obsidianStep2Item3: "コピーボタンをクリックします。",
        obsidianStep3: "OmniFlows の設定",
        obsidianStep3Text: "OmniFlows のオプションページを開き、詳細を入力します：",
        obsidianStep3Protocol: "プロトコル：http を選択。",
        obsidianStep3Port: "ポート：通常は 27123。",
        obsidianStep3Key: "API キー：コピーしたキーを貼り付けます。",
        obsidianTrouble1Title: "接続に失敗しましたか？",
        obsidianTrouble1Text1: "プロトコルの不一致：http が選択されているか確認してください。",
        obsidianTrouble1Text2: "プラグインの状態：Active（緑色）になっているか確認してください。",
        obsidianTrouble1Text3: "ポートの競合：他のアプリが同じポートを使っていないか確認してください。",

        // Notion Setup
        notionTitle: "Notion 統合ガイド",
        notionSubtitle: "OmniFlows を Notion ワークスペースに接続します。",
        notionStep1: "インテグレーションの作成",
        notionStep1Text: "「内部インテグレーション」を作成する必要があります。",
        notionStep1Item1: "notion.so/my-integrations にアクセスします。",
        notionStep1Item2: "+ New integration をクリックします。",
        notionStep1Item3: "名前を入力して保存します。",
        notionStep1Item4: "シークレットをコピーします。",
        notionStep2: "ページとの接続",
        notionStep2Text: "Notion ページでインテグレーションを許可します。",
        notionStep2Item1: "Notion で新しいページを作成します。",
        notionStep2Item2: "「...」をクリックします。",
        notionStep2Item3: "「コネクトを追加」で OmniFlows を検索します。",
        notionStep2Item4: "確認します。",
        notionStep3: "ページ ID の取得",
        notionStep3Text: "URL から ID を取得します。",
        notionStep3Item1: "ページの URL をコピーします。",
        notionStep3Item2: "URL の末尾にある 32 文字の文字列が ID です。",
        notionExampleUrl: "URL の例：",
        notionExampleId: "ID は ... です。",
        notionStep4: "OmniFlows での完了",
        notionStep4Text: "オプションにシークレットと ID を貼り付けます。",
        notionAutoSetupTitle: "自動セットアップ",
        notionAutoSetupText: "最初の保存時にデータベースが自動作成されます。",
        notionTrouble1Title: "オブジェクトが見つかりません",
        notionTrouble1Text1: "ステップ 2（コネクトの追加）が完了しているか確認してください。",
        notionTrouble2Title: "データベース ID vs ページ ID：",
        notionTrouble2Text1: "通常はページ ID を使用します。",

        // Common
        troubleshootingTitle: "トラブルシューティング",
        backToHome: "← ホームに戻る"
    },
    "zh-TW": {
        // Home
        heroTitle: "捕捉閱讀之流",
        heroSub: "<span class='hero-highlight'>以此構築你的私域知識體系。</span>OmniFlows 捕捉閱讀軌跡，將碎片化瀏覽轉化為結構化知識資產。",
        ctaLearnMore: "立即體驗",
        demoCapture: "一鍵捕捉：自動保留語義塊完整上下文。",
        demoReview: "知識回顧：AI 生成的每日洞察與總結。",
        demoInsight: "每日摘要：AI 驅動的主題與要點抽取。",
        demoSync: "無縫同步：已支援 Obsidian, Notion 與 Google Drive。",
        whyOmniFlows: "為何選擇 OmniFlows?",
        case1Title: "閱讀深度模型",
        case1Text: "不只是計時。我們通過停頓和滾動深度識別真正的深讀行為。",
        case2Title: "語義塊捕捉",
        case2Text: "捕捉完整的邏輯單元。每一個高亮都自動保留其原始語義背景。",
        case3Title: "跨平台同步",
        case3Text: "將你的知識資產直接導出到 Obsidian、Notion 或私有雲。",
        case4Title: "自定義標籤",
        case4Text: "通過多選標籤組織你的高亮，助你構建主題化的知識體系。",
        integHeader: "知識匯出，無縫持久",
        integSub: "OmniFlows 確保你的數據不再是孤島。通過深度的跨平台集成，構築你的終身知識庫。",
        integ1Title: "Obsidian 同步",
        integ1Text: "實時將瀏覽軌跡和知識項同步到你的 Obsidian 庫。",
        integ2Title: "Google Drive 備份",
        integ2Text: "安全地將所有捕獲的數據和配置備份到你的個人雲端。",
        integ3Title: "本地大模型支持",
        integ3Text: "在本地運行分類和摘要，實現最高的隱私和性能。",
        integ4Title: "Notion 集成",
        integ4Text: "將高亮直接存儲到 Notion 數據庫，並自動填充結構化屬性。",
        footerTagline: "構築數位記憶的未来。",
        footerResources: "集成指南",
        footerSupport: "技術支持",
        footerLegal: "法律條款",
        footerPrivacy: "隱私政策",
        footerObsidianGuide: "Obsidian",
        footerNotionGuide: "Notion",

        // Obsidian Setup
        obsidianTitle: "Obsidian 集成指南",
        obsidianSubtitle: "配置 Local REST API 插件，將 OmniFlows 連接至您的筆記庫。",
        obsidianStep1: "安裝插件",
        obsidianStep1Text: "OmniFlows 通過 Local REST API 插件與 Obsidian 通信。",
        obsidianStep1Item1: "打開 Obsidian 設置，進入“第三方插件 (Community plugins)”。",
        obsidianStep1Item2: "點擊“瀏覽 (Browse)”並搜索 Local REST API。",
        obsidianStep1Item3: "點擊安裝並啟用插件。",
        obsidianStep2: "獲取 API Key",
        obsidianStep2Text: "啟用後，您需要複製授權令牌。",
        obsidianStep2Item1: "進入 Local REST API 插件的設置頁面。",
        obsidianStep2Item2: "找到 API Key 部分。",
        obsidianStep2Item3: "點擊複製按鈕。",
        obsidianStep3: "配置插件能力",
        obsidianStep3Text: "打開 OmniFlows 插件的“選項”頁面並填寫：",
        obsidianStep3Protocol: "Protocol: 請選擇 http。",
        obsidianStep3Port: "Port: 通常為 27123。",
        obsidianStep3Key: "API Key: 貼上你在上一步複製的密鑰。",
        obsidianTrouble1Title: "連接失敗？",
        obsidianTrouble1Text1: "協議不匹配：確保在 OmniFlows 中選擇了 http。目前不支持 HTTPS。",
        obsidianTrouble1Text2: "插件狀態：確保 Obsidian 中的插件狀態顯示為綠色“Active”。",
        obsidianTrouble1Text3: "端口衝突：檢查是否有其他程序佔用了相同的端口。",

        // Notion Setup
        notionTitle: "Notion 集成指南",
        notionSubtitle: "將 OmniFlows 連接至 Notion 工作區。",
        notionStep1: "創建分身 (Integration)",
        notionStep1Text: "您需要創建一個“內部分身”。",
        notionStep1Item1: "訪問 notion.so/my-integrations。",
        notionStep1Item2: "點擊 “+ New integration”。",
        notionStep1Item3: "命名為 OmniFlows 並提交。",
        notionStep1Item4: "複製 “Internal Integration Secret”。",
        notionStep2: "準備頁面並關聯",
        notionStep2Text: "在 Notion 頁面中顯式授予存取權限。",
        notionStep2Item1: "在 Notion 中創建一個新頁面。",
        notionStep2Item2: "點擊頁面右上角的 “...”。",
        notionStep2Item3: "選擇 “Add connections” 並搜尋 OmniFlows。",
        notionStep2Item4: "確認關聯。",
        notionStep3: "獲取 Page ID",
        notionStep3Text: "從 URL 中獲取 ID。",
        notionStep3Item1: "複製該頁面的連結。",
        notionStep3Item2: "連結末尾那串 32 位的字符即為 Page ID。",
        notionExampleUrl: "示例連結：",
        notionExampleId: "ID 是 ...。",
        notionStep4: "在插件中完成設置",
        notionStep4Text: "貼上密鑰和 Page ID。",
        notionAutoSetupTitle: "自動化設置",
        notionAutoSetupText: "第一次保存時將自動創建資料庫。",
        notionTrouble1Title: "找不到對象？",
        notionTrouble1Text1: "請確認已完成第 2 步（添加連接）。",
        notionTrouble2Title: "資料庫 ID vs 頁面 ID：",
        notionTrouble2Text1: "通常使用頁面 ID。",

        // Common
        troubleshootingTitle: "故障排查",
        backToHome: "← 返回首頁"
    }
};

const languageSelectId = "language-select";

function setLanguage(lang) {
    try {
        const t = translations[lang] || translations.en;
        document.querySelectorAll("[data-i18n]").forEach(el => {
            const key = el.getAttribute("data-i18n");
            const translation = t[key];
            if (translation) {
                // Special handling for HTML segments
                if (key === "heroSub" || key.includes("Subtitle") || key.includes("Text")) {
                    el.innerHTML = translation;
                } else {
                    el.textContent = translation;
                }
            }
        });
        document.documentElement.lang = lang;
        localStorage.setItem("omni-lang", lang);

        // Update select values if they exist on the page
        const select = document.getElementById(languageSelectId);
        if (select) {
            select.value = lang;
        }
    } catch (e) {
        console.error("Language switch failed:", e);
    }
}

function initI18n() {
    const languageSelect = document.getElementById(languageSelectId);
    let savedLang = "en";
    try {
        savedLang = localStorage.getItem("omni-lang");
    } catch (e) { }

    if (!savedLang) {
        const navLang = navigator.language.toLowerCase();
        if (navLang.startsWith("zh")) {
            savedLang = (navLang.includes("tw") || navLang.includes("hk") || navLang.includes("hant")) ? "zh-TW" : "zh-CN";
        } else if (navLang.startsWith("de")) {
            savedLang = "de";
        } else if (navLang.startsWith("fr")) {
            savedLang = "fr";
        } else if (navLang.startsWith("ja")) {
            savedLang = "ja";
        } else {
            savedLang = "en";
        }
    }

    if (languageSelect) {
        languageSelect.value = savedLang;
        languageSelect.addEventListener("change", e => {
            const lang = e.target.value;
            setLanguage(lang);
            // If trackEvent is available (from analytics), use it
            if (typeof trackEvent === 'function') {
                trackEvent('set_language', { language: lang });
            }
        });
    }

    setLanguage(savedLang);
}

// Auto-init on DOMContentLoaded
document.addEventListener("DOMContentLoaded", initI18n);
